volumes:
  pg_data_production:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: flintman16/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: flintman16/foodgram_frontend   # уже nginx с билдом внутри
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
