version: "3.8"

volumes:
  pg_data_production:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    image: flintman16/foodgram_backend:latest
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/app/static
      - media:/app/media
    command: >
      bash -c "
      for i in {1..60}; do
        (echo > /dev/tcp/db/5432) >/dev/null 2>&1 && break;
        echo 'Waiting for db...'; sleep 2;
      done;
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn foodgram_backend.wsgi:application --bind 0.0.0.0:8000"


  frontend:
    image: flintman16/foodgram_frontend:latest
    depends_on:
      - backend
    ports:
      - "80:80"
    
    volumes:
      - static:/static
      - media:/media
