TAG_NAME_MAX_LENGTH = 32
TAG_SLUG_MAX_LENGTH = 32

INGREDIENT_NAME_MAX_LENGTH = 128
MEASUREMENT_UNIT_MAX_LENGTH = 64

RECIPE_NAME_MAX_LENGTH = 256
COOKING_TIME_MIN_VALUE = 1

INGREDIENT_AMOUNT_MIN_VALUE = 1
