server {
    listen 80;
    server_name foodgram.3utilities.com localhost;

    client_max_body_size 10M;
    server_tokens off;

    # React SPA (главная страница)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    # React assets (фронтенд-статика)
    location /static/ {
        root /usr/share/nginx/html;
    }

    # Вся Django статика
    location /backend_static/ {
        alias /static/;
    }

    # Медиа (загруженные пользователями файлы)
    location /media/ {
        alias /media/;
    }

    # Django админка
    location /admin/ {
    proxy_pass http://foodgram-back:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    }

    # API
    location /api/ {
        proxy_pass http://foodgram-back:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # ReDoc (документация API)
    location /api/docs/ {
    alias /usr/share/nginx/html/api/docs/;
    index redoc.html;
    }


}
