# Generated by Django 3.2.3 on 2025-10-02 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20251002_0517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('user', 'author'), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
